---
- name: Add dojo user account
  user:
    name: "{{item}}"
    comment: "Dojo jumpstation account"
  with_items:
    - dojo1
    - dojo2

- name: install vnc and applications environment
  apt: pkg={{item}} state=present force=yes
  with_items:
    - xfce4
    - firefox
    - chromium-browser
    - xfce4-goodies
    - tightvncserver
    - xfonts-base
    - chromium-browser

- name: install vnc configuration
  sudo: yes
  sudo_user: "{{item}}"
  copy: src=.Xauthority dest=/home/{{item}}/.Xauthority force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- sudo: yes
  sudo_user: "{{item}}"
  file:
    path: "/home/{{item}}/.vnc"
    state: directory
    owner: "{{item}}"
    mode: 0755
  with_items:
    - dojo1
    - dojo2

- name: set vnc password
  sudo: yes
  sudo_user: "{{item}}"
  command: "bash -c 'echo d0j04fun | vncpasswd -f > passwd && chmod 600 passwd'"
  args:
    creates: /home/{{item}}/.vnc/passwd
    chdir: /home/{{item}}/.vnc/
  with_items:
    - dojo1
    - dojo2

- name: install vnc configuration
  copy: src=xstartup dest=/home/{{item}}/.vnc/xstartup force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- name: install vnc init script
  template:
    src: vncserver@.service
    dest: /etc/systemd/system/vncserver-{{item}}@.service
    mode: 0644
    owner: root
  notify:
    - restart vnc
  with_items:
    - dojo1
    - dojo2

- name: Start VNC
  systemd:
    state: started
    enabled: yes
    name: vncserver-{{item.user}}@{{item.display}}
  with_items:
    - user: dojo1
      display: 1
    - user: dojo2
      display: 2
