---
- name: Add dojo user account
  user:
    name: dojo
    comment: "Dojo jumpstation account"

- name: install xfce
  apt: pkg={{item}} state=present force=yes
  with_items:
    - xfce4
    - firefox
    - chromium-browser
    - xfce4-goodies
    - tightvncserver
    - xfonts-base
    - chromium-browser

- name: install vnc configuration
  sudo: yes
  sudo_user: dojo
  copy: src=.Xauthority dest=/home/dojo/.Xauthority force=yes mode=700 owner=dojo

- sudo: yes
  sudo_user: dojo
  command: mkdir -p /home/dojo/.vnc/

- name: set vnc password
  sudo: yes
  sudo_user: dojo
  command: echo "d0j04fun" | vncpasswd -f > /home/dojo/.vnc/passwd
    creates: /home/dojo/.vnc/passwd

- name: install vnc configuration
  copy: src={{item}} dest=/home/dojo/.vnc/{{item}} force=yes mode=700 owner=dojo
  with_items:
      - xstartup

- name: install vnc init script
  copy: src=vncserver@.service dest=/etc/systemd/system/vncserver@.service mode=0755 owner=root
  notify:
    - restart vnc

- name: Start VNC
  systemd:
    state: started
    enabled: yes
    name: vncserver@1
