---
- name: Add dojo user account
  user:
    name: "{{item}}"
    comment: "Dojo jumpstation account"
  with_items:
    - dojo1
    - dojo2

- name: "Create jumpstation ssh key to all other servers"
  sudo: yes
  sudo_user: "{{item}}"
  command: ssh-keygen -t rsa -b 2048 -f /home/{{item}}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{item}}/.ssh/id_rsa
  with_items:
    - dojo1
    - dojo2

- name: "Add pub key to authorized_keys"
  sudo: yes
  sudo_user: "{{item}}"
  authorized_key:
    user: "{{item}}"
    state: present
    key: "{{ lookup('file', '/home/{{item}}/.ssh/id_rsa.pub') }}"
  delegate_to: delegate.host
  with_items:
    - dojo1
    - dojo2

- name: "Copy dojo public key over all LAB servers"
  synchronize:
    src: /home/{{item.user}}/.ssh/{{item.user}}/authorized_keys
    dest: rsync://{{item.host}}/home/{{item.user}}/.ssh/
  delegate_to: delegate.host
  with_items:
    - user: dojo1
      host: monitoring-node
    - user: dojo2
      host: monitoring-node
    - user: dojo1
      host: ci-node
    - user: dojo2
      host: ci-node
    - user: dojo1
      host: ci-repo
    - user: dojo2
      host: ci-repo
    - user: dojo1
      host: mongodb-node
    - user: dojo2
      host: mongodb-node
    - user: dojo1
      host: app-server-node-1
    - user: dojo2
      host: app-server-node-1
    - user: dojo1
      host: app-server-node-2
    - user: dojo2
      host: app-server-node-2
    - user: dojo1
      host: app-server-node-3
    - user: dojo2
      host: app-server-node-3
    - user: dojo1
      host: app-server-node-4
    - user: dojo2
      host: app-server-node-4

- name: install vnc and applications environment
  apt: pkg={{item}} state=present force=yes
  with_items:
    - xfce4
    - firefox
    - chromium-browser
    - xfce4-goodies
    - tightvncserver
    - xfonts-base
    - chromium-browser

- name: install vnc configuration
  sudo: yes
  sudo_user: "{{item}}"
  copy: src=.Xauthority dest=/home/{{item}}/.Xauthority force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- sudo: yes
  sudo_user: "{{item}}"
  file:
    path: "/home/{{item}}/.vnc"
    state: directory
    owner: "{{item}}"
    mode: 0755
  with_items:
    - dojo1
    - dojo2

- name: set vnc password
  sudo: yes
  sudo_user: "{{item}}"
  command: "bash -c 'echo d0j04fun | vncpasswd -f > passwd && chmod 600 passwd'"
  args:
    creates: /home/{{item}}/.vnc/passwd
    chdir: /home/{{item}}/.vnc/
  with_items:
    - dojo1
    - dojo2

- name: install vnc configuration
  copy: src=xstartup dest=/home/{{item}}/.vnc/xstartup force=yes mode=700 owner={{item}}
  with_items:
    - dojo1
    - dojo2

- name: install vnc init script
  template:
    src: vncserver@.service
    dest: /etc/systemd/system/vncserver-{{item}}@.service
    mode: 0644
    owner: root
  notify:
    - restart vnc
  with_items:
    - dojo1
    - dojo2

- name: Start VNC
  systemd:
    state: started
    enabled: yes
    name: vncserver-{{item.user}}@{{item.display}}
  with_items:
    - user: dojo1
      display: 1
    - user: dojo2
      display: 2


